## <u>Business Analytics & AI Insight Generation

In [4]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from IPython.display import display

# pip install kaleido

In [5]:
import os

for file in os.listdir():
    print(file)

BA_Superstore.ipynb
ERRORS.docx
insights_report.txt
Interview Answers.docx
Sample - Superstore.csv
~$terview Answers.docx

In [6]:
df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.info()
df.head()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Year'] = df['Order Date'].dt.year

df['Month'] = df['Order Date'].dt.strftime('%b')

df['Month_Number'] = df['Order Date'].dt.month

KPI Calculation :-

In [10]:
total_sales = df['Sales'].sum()

total_profit = df['Profit'].sum()

total_orders = df['Order ID'].nunique()

avg_order = total_sales / total_orders

print("Total Sales:", round(total_sales,2))
print("Total Profit:", round(total_profit,2))
print("Total Orders:", total_orders)
print("Average Order Value:", round(avg_order,2))

Total Sales: 2297200.86
Total Profit: 286397.02
Total Orders: 5009
Average Order Value: 458.61

#### Top region trend :

In [11]:
region_sales = (df.groupby('Region')['Sales'].sum().sort_values(ascending=False))

region_sales

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

In [12]:
# finding best region:
top_region = region_sales.idxmax()

top_region_sales = region_sales.max()

print("Top Region:", top_region)

print("Sales:", round(top_region_sales,2))

Top Region: West
Sales: 725457.82

#### Top Category trend:

In [13]:
category_sales = (df.groupby('Category')['Sales'].sum().sort_values(ascending=False))
category_sales

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [14]:
# finding best category:
top_category = category_sales.idxmax()

top_category_sales = category_sales.max()

print("Top Category:", top_category)

print("Sales:", round(top_category_sales,2))

Top Category: Technology
Sales: 836154.03

#### Monthly Sales Trend

In [15]:

monthly_sales = (df.groupby(df['Order Date'].dt.to_period('M'))['Sales'].sum().reset_index())
monthly_sales['Order Date'] = monthly_sales['Order Date'].astype(str)
monthly_sales.head()

  Order Date      Sales
0    2014-01  14236.895
1    2014-02   4519.892
2    2014-03  55691.009
3    2014-04  28295.345
4    2014-05  23648.287

In [16]:
# Monthly sales visualization:
fig = px.line(
    monthly_sales,
    x='Order Date',
    y='Sales',
    title='Monthly Sales Trend'
)

fig.show()

In [18]:
fig.write_image("Monthly Sales Trend.png")

#### Region Sales Chart:

In [ ]:
region_df = (df.groupby('Region')['Sales'].sum().reset_index())

fig = px.bar(
    region_df,
    x='Region',
    y='Sales',
    title='Sales by Region'
)

fig.show()

In [19]:
fig.write_image("Sales by Region.png")

#### Category Sales Chart:

In [20]:
category_df = (df.groupby('Category')['Sales'].sum().reset_index())

fig = px.bar(
    category_df,
    x='Category',
    y='Sales',
    title='Sales by Category'
)

fig.show()

In [21]:
fig.write_image("Sales by Category.png")

#### Profit Analysis and Chart:

In [22]:
region_profit = (df.groupby('Region')['Profit'].sum().reset_index())
fig = px.bar(
    region_profit,
    x='Region',
    y='Profit',
    title='Profit by Region'
)

fig.show()

In [23]:
fig.write_image("Profit by Region.png")

#### Top 10 Product Chart

In [ ]:
top_products = (df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10).reset_index())

fig = px.bar(
    top_products,
    x='Sales',
    y='Product Name',
    orientation='h',
    title='Top 10 Products'
)

fig.show()

In [24]:
fig.write_image("Top 10 Products.png")

## AI Insight Generation (Rule-Based)

In [ ]:
insights = []

insights.append(
    f"Total sales reached ${total_sales:,.0f}."
)

insights.append(
    f"Total profit reached ${total_profit:,.0f}."
)

insights.append(
    f"{top_region} was the highest revenue-generating region."
)

insights.append(
    f"{top_category} was the best-performing category."
)

#### Growth Analysis

In [ ]:
latest_month = monthly_sales.iloc[-1]['Sales']

previous_month = monthly_sales.iloc[-2]['Sales']

if latest_month > previous_month:
    
    insights.append(
        "Sales increased in the latest month."
    )
    
else:
    
    insights.append(
        "Sales decreased in the latest month."
    )

#### Business Recommendations

In [ ]:
recommendations = []

recommendations.append(
    f"Increase focus on {top_region} region due to strong sales performance."
)

recommendations.append(
    f"Expand inventory for {top_category} products."
)

recommendations.append(
    "Monitor low-profit regions for cost optimization."
)

recommendations.append(
    "Use monthly trend tracking for forecasting future demand."
)

In [ ]:
# Display Insights
print("AI GENERATED BUSINESS INSIGHTS")
print("-" * 50)

for item in insights:
    print("•", item)

AI GENERATED BUSINESS INSIGHTS
--------------------------------------------------
• Total sales reached $2,297,201.
• Total profit reached $286,397.
• West was the highest revenue-generating region.
• Technology was the best-performing category.
• Sales decreased in the latest month.

In [ ]:
# Display Recommendations
print("BUSINESS RECOMMENDATIONS")
print("-" * 50)

for item in recommendations:
    print("•", item)

BUSINESS RECOMMENDATIONS
--------------------------------------------------
• Increase focus on West region due to strong sales performance.
• Expand inventory for Technology products.
• Monitor low-profit regions for cost optimization.
• Use monthly trend tracking for forecasting future demand.

##### Export:-

In [ ]:
with open("insights_report.txt", "w") as f:

    f.write("BUSINESS ANALYTICS REPORT\n\n")

    f.write("KEY INSIGHTS\n")

    for item in insights:
        f.write(f"- {item}\n")

    f.write("\nRECOMMENDATIONS\n")

    for item in recommendations:
        f.write(f"- {item}\n")

print("Report Generated Successfully")

Report Generated Successfully

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////